version: 0.2

# Use Java8 image.

env:
  variables:
    ACCOUNT: 0000
    APP: hoge

phases:
  install:
    commands:
      - echo Nothing to do in install...
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ap-northeast-1)
  build:
    commands:
      - echo Building jar and docker image...
      - mvn install -DskipTests=true
      - cd ./$APP
      - mvn clean package docker:build
      - docker tag ~~~/$APP:latest $ACCOUNT.dkr.ecr.ap-northeast-1.amazonaws.com/~~~/$APP:latest
  post_build:
    commands:
      - echo Uploading the docker image...
      - docker push $ACCOUNT.dkr.ecr.ap-northeast-1.amazonaws.com/~~~/$APP:latest
